Código Refatorado
fga-eps-mds/2021-2-MeasureSoftGram-CLI pull request #11
Opened 2022-03-23 22:33 UTC by LucasPimentel123

# Código Refatorado 

## Descrição
Código refatorado e com adição de IDs para as préconfigurações

## Porque este Pull Request é necessário?
O código estava confuso e mal otimizado

2022-03-24 18:32 UTC, Rhuancpq requested changes

2022-03-24 18:32 UTC, Rhuancpq commented on measuresoftgram/create.py
> +def define_id():
Vamos em pontos:

1. O ID deveria ser alfanumérico
2. O ID acontece junto com a criação da pré config, deve ocorrer no backend por estar atrelado ao negócio e a persistência

2022-03-24 18:32 UTC, Rhuancpq commented on measuresoftgram/create.py
> +def define_id():
Github bugou e não mostra

2022-03-24 21:33 UTC, igor-paiva commented
Título e corpo do PR não condizem com as mudanças feitas nele

2022-04-08 22:54 UTC, igor-paiva commented
Devido a todas as mudanças e conversas que tivemos com o cliente, vamos deixar esse pull request de lado, porque está refatorando algo que não vamos mais usar.

2022-04-08 22:54 UTC, closed without merging